server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:Null123456/springcloud-config.git
          uri: https://github.com/Null123456/springcloud-config.git
          search-paths:
            - springcloud-config
          force-pull: true
          username: 1638343272@qq.com
          password: lyp97nlf..
      label: main

rabbitmq:
  host: localhsot
  port: 5672
  username: guest
  password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

##rabbitmq配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
