server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能 ，利用微服务名进行路由
      routes:
        - id: payment_routh             #路由的id，没有固定规则，但要求唯一，建议配合服务名使用
          #uri: http://localhost:8001     #匹配后的服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:                     #断言，路径相匹配的进行路由
            - Path=/get/**
        - id: payment_routh2             #路由的id，没有固定规则，但要求唯一，建议配合服务名使用
          #uri: http://localhost:8001     #匹配后的服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:                     #断言，路径相匹配的进行路由
            - Path=/getLB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://localhost:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    instance:
      hostname: cloud-gateway-service
